name: Build and Deploy React App to CloudFront
on:
  push:
    branches: [ master ]
jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install Dependencies
      run: |
        node --version
        npm install

    - name: Build Static Website
      run: npm run build
    
    - name: Configure AWS CLI
      run: aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} && aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }} && aws configure set region us-west-2

    - name: Copy files to S3 bucket
      run: |
        aws s3 sync dist/ s3://${{ secrets.BUCKET }} --delete

    - name: Create invalidation for cloudfront deploy
      run: |
        aws cloudfront create-invalidation \
          --distribution-id ${{ secrets.DIST_ID }} \
          --paths "/*"
